user_mobile_profile:
  email: sdet.jurnal_mobile+1@notnotnot.com
  password: Password123

user_invalid_password:
  email: sdet.jurnal_mobile+1@notnotnot.com
  password: Password12345
  error_message: 'Wrong Email or Password'

user_invalid_email:
  email: abcdefghijklmnopqrstuvwxyznotnotnot.om
  password: Password123
  error_message: 'Invalid email or password'

user_empty_password:
  email: sdet.jurnal_mobile+1@notnotnot.com
  password:
  error_message: "Email or Password can't be blank"

user_empty_email:
  email:
  password: Password12345
  error_message: "Email or Password can't be blank"

user_sales_order:
  email: sdet.jurnal_mobile+3@notnotnot.com
  password: Password123

user_mobile_sales_invoice:
  email: sdet.jurnal_mobile+2@notnotnot.com
  password: Password123

user_mobile_purchase_invoice:
  email: sdet.jurnal_mobile+4@notnotnot.com
  password: Password123

user_mobile_purchase_order:
  email: sdet.jurnal_mobile+5@notnotnot.com
  password: Password123

user_mobile_expense:
  email: sdet.jurnal_mobile+6@notnotnot.com
  password: Password123

user_mobile_sales_quote:
  email: sdet.jurnal_mobile+7@notnotnot.com
  password: Password123

user_mobile_cash_and_bank:
  email: sdet.jurnal_mobile+8@notnotnot.com
  password: Password123

user_mobile_contact_without_transaction:
  email: sdet.jurnal_mobile+9@notnotnot.com
  password: Password123

user_mobile_setting_company:
  email: sdet.jurnal_mobile+10@notnotnot.com
  password: Password123

user_mobile_setting_security:
  email: sdet.jurnal_mobile+11@notnotnot.com
  password: Password123

user_unregistered:
  email: sdet.jurnal_mobile+7777@notnotnot.com
  password: Password123
  
user_sales_invoice_return_roles:
  name: SDET invoice return
  email: sdet.jurnal.invoice@mailinator.com
  password: Password123

user_sales_order_quote_roles:
  name: SDET order quote
  email: sdet.jurnal.order@mailinator.com
  password: Password123

user_sales_payments_roles:
  name: SDET sales payments
  email: sdet.jurnal.sales_payment@mailinator.com
  password: Password123

user_sales_invoice_return_restricted_roles:
  name: SDET invoice return restricted
  email: sdet.jurnal.invoice_restricted@mailinator.com
  password: Password123

user_sales_order_quote_restricted_roles:
  name: SDET order quote restricted
  email: sdet.jurnal.order_restricted@mailinator.com
  password: Password123

user_sales_payments_restricted_roles:
  name: SDET payments restricted
  email: sdet.jurnal.payments_restricted@mailinator.com
  password: Password123

user_purchase_invoice_return_roles:
  name: SDET purchase invoice return
  email: sdet.jurnal.purchase_invoice_return@mailinator.com
  password: Password123

user_purchase_order_quote_roles:
  name: SDET purchase order quote
  email: sdet.jurnal.purchase_order_quote@mailinator.com
  password: Password123

user_purchase_payments_roles:
  name: SDET purchase payments
  email: sdet.jurnal.purchase_payment@mailinator.com
  password: Password123

user_purchase_invoice_restricted_roles:
  name: SDET purchases invoice restricted
  email: sdet.jurnal.purchases_inv_restricted@mailinator.com
  password: Password123

user_purchase_order_restricted_roles:
  name: SDET purchases order restricted
  email: sdet.jurnal.purchases_order_restricted@mailinator.com
  password: Password123

user_purchase_payments_restricted_roles:
  name: SDET purchases payments restricted
  email: sdet.jurnal.purchases_payments_restricted@mailinator.com
  password: Password123

user_create_products:
  email: sdet.jurnal_mobile+12@notnotnot.com
  password: Password123  

user_approval_log_owner_roles:
  email: sdet.jurnal_mobile+13@notnotnot.com
  password: Password123

user_approval_log_approval_role_1:
  email: sdet.jurnal_mobile.approval1@mailinator.com
  password: Password123

user_approval_log_buyer_role_1:
  email: sdet.jurnal_mobile.buyer1@mailinator.com
  password: Password123