source 'https://rubygems.org'
ruby '2.5.0'

gem 'appium_lib'
gem 'appom', git: 'https://github.com/firstlutfi/appom.git', branch: 'master'
gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
# gem 'chilkat'
gem 'chunky_png', '1.3.7'
gem 'cucumber', '3.1.2'
gem 'cuke_sniffer'
gem 'dotenv'
gem 'faker', '>= 2.15.1'
gem 'foreman', '~> 0.87.2'
gem 'gmail', '~> 0.6.0'
gem 'google-api-client'
gem 'imatcher', '0.1.5'
gem 'new_data_magic', '~> 1.2'
gem 'os'
gem 'parallel_tests'
gem 'pdf-reader'
# gem 'pronto'
# gem 'pronto-flay', require: false
# gem 'pronto-rubocop', require: false
gem 'base64'
gem 'pry'
gem 'pry-byebug'
gem 'rake'
gem 'report_builder'
gem 'require_all'
gem 'roo', '~> 2.8.0'
gem 'roo-xls'
gem 'rspec', '~> 3.5'
gem 'rspec-expectations', '3.5.0'
gem 'rubocop', '0.59.2', require: false
gem 'rubyXL'
gem 'selenium-webdriver', '3.141.0'
gem 'show_me_the_cookies'
gem 'site_prism', '2.16'
gem 'site_prism-table'
gem 'spreadsheet'
gem 'syntax'
gem 'touch_action'
